.github/workflows/build.yml
server/main.py
server/ome_node.py

You will need to invite me to be a maintainer of this repo or merge each of my pull requests.
* https://github.com/ISKME/OME/settings/access

Add GitHub Action build

---

.github/workflows/build.yml
.pre-commit-config.yaml
Notes.org
README.md
fe/src/components/CatalogCard.vue
fe/src/components/ChannelList.vue
fe/src/pages/channeldetails.vue
server/main.py
server/ome_node.py
server/schemas.py

Add pre-commit

---

docs/.github/workflows/sphinx.yml
docs/Makefile
docs/README.md
docs/conf.py
docs/index.md
docs/make.bat

```
python3 -m venv .venv
source .venv/bin/activate
pip install --upgrade pip
pip install sphinx myst-parser
cd docs
make epub # or make html
```

Add docs with Sphinx

---

.github/workflows/sphinx.yml
src/education_resource.py
src/pedigree_record.py

Define EducationResource and PedigreeRecord

---

.github/workflows/build.yml
src/inn_article_001.txt
src/nntplib_tests.py

Run inn2 in the build GitHub Action

---

.github/workflows/build.yml
.pre-commit-config.yaml
server/ome_node.py
tests/test_ome_node.py

Adds pytests:
* `test_get_client()`
* `test_channels()`
* `test_channel_summary()`

pytest tests/test_ome_node.py

---

.github/workflows/sphinx.yml
CONTRIBUTING.md
docs/conf.py

Automatically document APIs with
* https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html
* https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html

Sphinx: Add autodoc and napoleon

---

.github/workflows/build.yml
README.md

https://github.com/cclauss/apt-get-inn2-docker
For local development and testing, start the INN2 server with:
% `docker run --rm -t -p119:119 -p563:563 cclauss/inn`

Document INN2 running in a local Docker container

---

.gitignore

.gitignore:  fe2/node_modules/

---

Dockerfile
Pipfile
Pipfile.lock
README.md
docs/overview.md
server/main.py
server/ome_node.py

Use pipenv shell to run FastAPI

---

Dockerfile
README.md

```diff
- CMD ["uv", "run", "fastapi", "dev", "--port=5001", "server/main.py"]
+ CMD ["uv", "run", "fastapi", "dev", "--host=0.0.0.0", "--port=5001", "server/main.py"]
```

fastapi dev --host=0.0.0.0 --port=5001 server/main.py

---

index.md
pyproject.toml

This should upgrade from Sphinx v6 to v8.  https://pypi.org/project/Sphinx

Docs: Remove rst-to-myst

---

.pre-commit-config.yaml
CONTRIBUTING.md

Start by creating your own `fork` of the `Open-Metadata-Exchange` GitHub repository.
Substitute your GitHub username in the steps below: `<your_GitHub_username>`
* Go to https://github.com/<your_GitHub_username>/Open-Metadata-Exchange.
* If that page already exists then you already have your own fork.
* If that page does not exist, go to https://github.com/ISKME/Open-Metadata-Exchange and click the `Fork` button in the upper right of the page.
We can switch to the terminal to create a local directory where you can make changes and submit them as pull requests.
* `git clone https://github.com/<your_GitHub_username>/Open-Metadata-Exchange` will make a local copy.  Make sure you use `<your_GitHub_username>`!!
* `cd Open-Metadata-Exchange`  # Going inside this new directory is important.
* …

CONTRIBUTING.md: Add Starting from scratch instructions

---

.github/workflows/build.yml
static/index.html

Add more options to static/index.html

---

static/index.html

Add FastAPI endpoints to static/index.html

---

docker-compose.yml

imls-react depends_on fastapi-server
fastapi-server depends_on internetnews-server

docker compose depends-on

---

docker-compose.yml
server/ome_node.py
tests/test_ome_node.py

```python
AUSTIN_PORT = 119
BOSTON_PORT = AUSTIN_PORT + 1000
```
```diff
internetnews-server-austin:
image: cclauss/inn
ports:
- 119:119
- 563:563
+ internetnews-server-boston:
+   image: cclauss/inn
+   ports:
+     - 1119:119
+     - 1563:563
```

Two InterNetNews servers: Austin and Boston

---

.github/dependabot.yml

Run dependabot on npm dependencies in /fe2

---

.pre-commit-config.yaml

Upgrade to ruff v0.8.1

---

.pre-commit-config.yaml

https://github.com/astral-sh/ruff/releases

Ruff v0.8.4 -> v0.8.6

---

.github/workflows/ci.yml
.pre-commit-config.yaml
docker-compose.yml
fe/README.md
scripts/create_newsgroup.sh

docker exec -it open-metadata-exchange-internetnews-server-austin-1 sh -c \
"ctlinnd newgroup oer.public && ctlinnd newgroup eric.public && ctlinnd newgroup openlibrary.public && cat db/active"

Rename newsgroup OER.public oer.public

---

Dockerfile
index.md
server/get_ome_plugins.py
server/newsgroups_view.py
server/plugins/qubes/README.md
templates/newsgroups.html

Make newsgroups webpage dynamic

---

CONTRIBUTING.md
server/card_editor.py
server/main.py
server/ome_node.py
tests/test_ome_node.py

Workaround for:
* greenbender/pynntp#95

Workaround for pynntp_client.list_newsgroups()

---

.pre-commit-config.yaml
pyproject.toml

Also...
% `pre-commit autoupdate`
```
[https://github.com/astral-sh/ruff-pre-commit] updating v0.12.0 -> v0.12.1
```
https://github.com/astral-sh/ruff/releases

tool.ruff.exclude = [".git/", "server/plugins/moodle/extract-mbz3.py"]

---

server/plugins/qubes/utils.py

* https://github.com/ISKME/Open-Metadata-Exchange/pull/203#pullrequestreview-3259532539

No need to pip install modules that are in the Python Standard Library

---

.pre-commit-config.yaml
pyproject.toml

```diff
- requires-python = "==3.13.*"
+ requires-python = ">=3.13.0"
```

Allow Python 3.14

---

docker-compose.yml
fe2/webpack-stats.json
scripts/create_newsgroups.py
server/plugins/qubes/README.md

Removed boston
Changed hostname
(cherry picked from commit 414d6cfd04c684ddece11efb5d00b4ed90eb73ff)

Modified docker for QUBES development
